# Generated by Django 3.1 on 2020-12-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
