# Generated by Django 3.1 on 2020-12-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_siteinfo_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='responce_time',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
